spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lw?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 20
    minIdle: 20
    maxActive: 200
    maxWait: 60000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678
    database: 7
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数
        max-idle: 10      # 连接池最大空闲连接
        min-idle: 5       # 连接池最小空闲连接
        max-wait: -1ms    # 连接池最大阻塞时间
      shutdown-timeout: 3000ms
jwt:
  expire: 86400000
  issuer: lw
  secret: 1245789
snowflake:
  workerId: 1
  dataCenterId: 1